### ISSUE TITLE
movies

### ISSUE THREAD

**Issue by ask-compu** [JimAllanson/api.ponycountdown.com#4]
you should put mlp movies such as equestria girls in a season 0, like rainbow rocks would be season 0 episode 2

**Comment by JimAllanson** [comment]
I'd rather not mix movies in with the TV episodes by creating a dummy season, as it could throw off some apps consuming the APIs, and leaves us with the problem of how to separate the EQG movies from the FiM one. I think if I were to add these in, I'd probably want to separate them into a different endpoint, or possibly a a separate API. I might add these in a future update.

**Comment by ask-compu** [comment]
you could add an ismovie boolean to each entry, false for episodes and true for movies

**Comment by JimAllanson** [comment]
I've added a new endpoint, /movies, that returns a full list of movies. Currently it just returns the EQG movies, but once we have a confirmed date for the FiM movie, I'll add that too. There's a "universe" field which indicates whether the movie is "equestria-girls" or "friendship-is-magic" (I made this a string rather than a boolean as you never know what Hasbro might come up with next).

**Comment by ask-compu** [comment]
would be nice if u had a number field for the movies to more easily indicate the order in which they aired, is well as an endpoint like /movie/1
